INHERIT: base.yml
site_description: Technical documentation for robotframework-paylo in Python and Robot Framework
site_url: https://angel-valdezzz.github.io/robotframework-paylo/
docs_dir: docs/en
site_dir: site
edit_uri: edit/main/docs/en/
theme:
  language: en
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: custom
    accent: custom
    toggle:
      icon: material/weather-night
      name: Dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: custom
    accent: custom
    toggle:
      icon: material/weather-sunny
      name: Light mode
plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: false
      fallback_to_build_date: true
      locale: en
      type: datetime
nav:
  - Home: index.md
  - User guide: guide.md
  - Keyword reference: keywords/index.html
  - Visual examples: examples.md
  - Development and publishing: development.md
